### PR TITLE
Victim Crasher Compact + Victim Crasher Overlay Design

### PR DESCRIPTION
**Pull request by VictimCrasher**
## Victim Crasher Compact
Based on Kerli1 and Kerli2, made it more compact so you only need 1 source.
  
### Design
\
[Video Demo](https://www.youtube.com/watch?v=b27MlLIurTw)

## Victim Crasher Overlay
My own take on Overlay design, best used for replay recording.
  
### Design
\
[Video Demo](https://www.youtube.com/watch?v=_8Ewz97_hGc)

### CODE REVIEW

**Comment by l3lackShark** [comment]
Thanks for your contribution! Our front-ender will review your code within the next couple of days.

**Comment by l3lackShark** [comment]
Will throw my two cents here: 
How about extending the text ticker right to the edges so it doesn't cut like on your video? 
image

**Comment by l3lackShark** [comment]
Actually no, it's good as is. I see the reason on why you did it that way now.

**Comment by l3lackShark** [comment]
image

The numbers are cut here. I believe the fix for this would be:

```css
.odometer .odometer-digit .odometer-value {
    width: 100%;
}

**Comment by VictimCrasher** [comment]
> The numbers are cut here. I believe the fix for this would be:
> 
> ```css
> .odometer .odometer-digit .odometer-value {
>     width: 100%;
> }
> ```

image

Thank you for pointing it out, but the problem seem to be on margin not on width
```css
.odometer .odometer-digit .odometer-value {
    margin: 0;
}
```

Pushing the update asap

**Comment by varkaria** [comment]
woa!! look beautiful tho ❤️

**Comment by Dartandr** [comment]
Please change folders names from Victim_Crasher_Compact to VictimCrasherCompact

**Comment by Dartandr** [comment]
In overlay text shadow on elements little bit cut, to fix it you need to remover overflow: hidden; in odometr.css in that block of code
```css
.odometer.odometer-auto-theme .odometer-digit .odometer-digit-inner, .odometer.odometer-theme-default .odometer-digit .odometer-digit-inner {
    text-align: left;
    display: block;
    position: absolute;
    top: 0;
    left: 0;
    right: 0;
    bottom: 0;
    overflow: hidden;
  }
```
and add height and overflow-y: hidden to all elements that uses odometr
Also after that probably you will need to add some padding from left and right to that elements to reduce shadow cuts on first and last number

**Comment by Dartandr** [comment]
don't you think to probably remove shadow from hpbar because it's looks kinda off when hp full or almost full  
image

**Comment by VictimCrasher** [comment]
Thank you for the review, I'll try to fix it by tonight.

> Please change folders names from Victim_Crasher_Compact to VictimCrasherCompact

I presume it also applies to Victim_Crasher_Overlay (?)

**Comment by Dartandr** [comment]
> I presume it also applies to Victim_Crasher_Overlay (?)

yes

**Comment by VictimCrasher** [comment]
> In overlay text shadow on elements little bit cut, to fix it  

Consider it done, workaround were made. 😂

> don't you think to probably remove shadow from hpbar because it's looks kinda off when hp full or almost full  

Yup kinda bugging me out, so I delete the shadow as you said.

image

---

### Additional Fixes:
Somehow the cut numbers on Compact is still showing up, I manage to fix them again.

image

**Comment by Dartandr** [comment]
Okay everything looks nice don't you mind to update images in readme after fixes and please use code crimson for it Xd

**Comment by VictimCrasher** [comment]
> Okay everything looks nice don't you mind to update images in readme after fixes and please use code crimson for it Xd

Consider it done 👍

**Review by Dartandr — APPROVED** [review]
lgtm

**Comment by l3lackShark** [comment]
Thanks!

**Pull request merged**
