### PR TITLE
(Hopefully) Fix performance issues on VictimCrasherOverlay

### PR DESCRIPTION
**Pull request by VictimCrasher**
### What has been changed:
- Change **scores, accuracy, ur** from odometer to countUp.js
- Remove odometer class from **h100, h50, h0** (So no animation whatsoever)

### Note:
**Combo** and **PP** is still using odometer, let me know if I need to convert that to countUp.js aswell.
Other performance-enhancing changes suggestion is always welcome.

### CODE REVIEW

**Comment by osugenics** [comment]
finally I can use my kinda garbage pc to use your pp counter without stutters (pretty much)

**Comment by VictimCrasher** [comment]
> finally I can use my kinda garbage pc to use your pp counter without stutters (pretty much)

Do you mind checking it to see if it fix the performance problem?

**Comment by osugenics** [comment]
> > finally I can use my kinda garbage pc to use your pp counter without stutters (pretty much)
> 
> Do you mind checking it to see if it fix the performance problem?
ok, maybe tomorrow. I still have to do some stuff.

**Comment by osugenics** [comment]
> > finally I can use my kinda garbage pc to use your pp counter without stutters (pretty much)
> 
> Do you mind checking it to see if it fix the performance problem?

ok so I checked, and turns out it does fix the issues. Even while OBS was running and recording, it still kept up with the map (like combo, acc, and pp). Whatever improvements you made, it sure did have an impact on my videos :)

**Comment by jooaooalmeida** [comment]
Fixed the issues for me too, now just need to fix it not being updated each 100ms, now im for sure going to use your overlay in my next videos +1 from me

**Comment by l3lackShark** [comment]
Thank you for fixing!

**Pull request merged**
