### PR TITLE
reComfortaa

### PR DESCRIPTION
**Pull request by Xyn0gen**
> *Song Selection*\
\
>*Gameplay*\
>

The font is called comfortaa. I'm not creative with names.
Also couldn't think of a design to fit a progress bar so I decided to do away with it.

### CODE REVIEW

**Comment by Dartandr** [comment]
Hello
In my opinion design itself needs improvements
1) Pp's and score rank need to be aligned to vertical center
2) difficulty and mapper font is too small and thin. Imagine scaling down this counter to size it would be on stream, it would be hardly readable 
3) Also underline on hits with different width looks kinda strange, probably would be better to make it static

**Comment by Xyn0gen** [comment]
>\
>

Added fade to overflowing diffculty and mapper text instead of using ellipses

**Comment by Dartandr** [comment]
I think you need to maybe align diff and mapper to center if it doesn't cover all size of a div.
Still not sure that this would work but give it a try. 
Another way this looks not balanced i guess
image

**Comment by Dartandr** [comment]
Everything else lgtm

**Comment by Xyn0gen** [comment]
Screenshot_2021-03-06 MiniCounter
Sorry for the delay, busy week.
Not sure if this is what you mean but this is what I thought when you said to align them in the center.
Unless you meant to align it so that difficulty is to the left and the name is centered.

**Comment by Dartandr** [comment]
Yeah that what i meant. Naah still not sure that it's looks good. Well just leave as it was before. I approve. It will be merged before next gosumemory release

**Review by Dartandr — APPROVED** [review]

**Comment by l3lackShark** [comment]
Thanks!

**Pull request merged**
