### PR TITLE
New pp counter

### PR DESCRIPTION
**Pull request by heagan01**
This is a new pp counter the SmolPPCounter

Menu:
image

Gameplay:
image

### CODE REVIEW

**Comment by l3lackShark** [comment]
Thanks for your contribution! Our Front-Ender will review your code within the next couple of days.

**Comment by Dartandr** [comment]
Hello
First of all you trying to add multiple counters at once "SmolPPCounter" and "Heagan1" are you sure that it's right?
also "Heagan1" has an api key there (recommending to reset it on https://osu.ppy.sh/p/api )
Then you need to add images to README.md

**Comment by heagan01** [comment]
ok im gonna fix that in abit, im just trying to add the smolppcounter folder

**Comment by heagan01** [comment]
fixed

**Comment by l3lackShark** [comment]
After some internal discussions we have decided to reject your pull request due to not meeting our design standards. Unfortunately we do not have strict rules for design and so I cannot directly pin-point to why exactly we have made the choice. Thanks for your contribution anyways. I wish you good luck.

**Pull request closed without merging**
